# Write your code here :-)
print("==================================")
print("Darth Plagus The Wise?")
print("Almost Heaven, West Virginia, Blue Ridge Mountains!")
print("==================================")
print("")
print("Hello, World!")
name = input("What is your name? ")
print(f"Hello, {name} ")